# Generated by Django 5.0 on 2024-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Name',
            field=models.IntegerField(choices=[(1, 'Ring'), (2, 'Bracelets'), (3, 'Earring'), (4, 'Chain'), (5, 'Ancklates')], default=1),
            preserve_default=False,
        ),
    ]
