# Generated by Django 5.0 on 2024-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Japp', '0007_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Name',
        ),
    ]
