# Generated by Django 5.0 on 2024-01-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japp', '0009_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.IntegerField(choices=[(1, 'Ring'), (2, 'Bracelets'), (3, 'Earring'), (4, 'Chain'), (5, 'Ancklates'), (6, 'Necklace')], verbose_name='PName'),
        ),
    ]
